# 데이터 전처리

## 인코딩(Encoding) 

 - Null,NaN값 처리
 
 - 문자형 -> 숫자형변환
 
###  label 인코딩, One Hot 인코딩

- label 인코딩 : 카테고리 피처 -> 코드형 숫자값 변환
    - LabelEncoder(),fit(),transform() 호출

- OneHot 인코딩 : : 피처값의 유형에 새로운 피처를 추가 해 고유값 컬럼에만 1 표시
                    나머지 컬럼에는 0표시
    - OneHotEncoder()
    - 주의할 점 : 1. 변환 전 모든 문자열 값이 숫자형 값으로 변환 되어야함
                  2. 입력값으로 2차원 데이터가 필요

In [4]:
from sklearn.preprocessing import LabelEncoder

##라벨인코딩

items=['노트북','TV','탭','휴대폰','모니터','에어컨','냉장고']

#LabelEncoder 객체 생성후 fit, transform

encoder = LabelEncoder()
encoder.fit(items)
label_en = encoder.transform(items)
print('인코딩 변환값:',label_en)

# 문자열 값 보기
print('인코딩 클래스 : ',encoder.classes_)
# 디코딩 원본값 보기 : encoder.inverse_transform([])

인코딩 값: [2 0 5 6 3 4 1]
인코딩 클래스 :  ['TV' '냉장고' '노트북' '모니터' '에어컨' '탭' '휴대폰']


In [11]:
#One-Hot 인코딩

from sklearn.preprocessing import LabelEncoder,OneHotEncoder
import numpy as np

# 숫자값 변환을 위해 라벨인코딩 
items=['노트북','TV','탭','휴대폰','모니터','에어컨','냉장고']

lencoder = LabelEncoder()
lencoder.fit(items)
labels=lencoder.transform(items)

# 2차원 데이터로 변환
label = labels.reshape(-1,1)

#원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(label)
onehot = oh_encoder.transform(label)

print('원핫 인코딩:\n',onehot.toarray())
print('원핫 인코딩 데이터 차원:',onehot.shape)

원핫 인코딩:
 [[0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
원핫 인코딩 데이터 차원: (7, 7)


pandas API를 활용해 원-핫 인코딩 더 쉽게 하기

- get dummies() 활용


In [12]:
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0

## 정규화와 표준화

### 표준화(Standardization) : Z - score

- 평균 0 분산1로 변환

xi_new = xi-mean(x)/std(x)

### 정규화(Normalization) : MinMaxScaler

- 데이터를 0과 1사이의 값으로 변환

xi_new = xi-min(x)/max(x)-min(x)

In [17]:
# 표준화

from sklearn.datasets import load_iris
import pandas as pd

#붓꽃데이터 로드 후 dataframe으로 변환

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)

print('feature 들의 평균값:\n',iris_df.mean())
print('feature 들의 분산값:\n',iris_df.var())

feature 들의 평균값:
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
feature 들의 분산값:
 sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [20]:
#StandardScaler 로 피쳐들을 한번에 표준화

from sklearn.preprocessing import StandardScaler

#StandardScaler 객체생성
scaler = StandardScaler()

# fit(), transform()호출
scaler.fit(iris_df)
iris_scaler=scaler.transform(iris_df)

# transform 시 스케일 변환된 데이터세트가 Numpy ndarray로 반환
# 이를 다시 dataframe으로 변환해야함
iris_df_scaler =pd.DataFrame(data=iris_scaler, columns=iris.feature_names) 
print('피쳐들의 평균값:\n',iris_df_scaler.mean())
print('피쳐들의 분산값:\n',iris_df_scaler.var())

피쳐들의 평균값:
 sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
피쳐들의 분산값:
 sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [21]:
# 표준화 MinMaxScaler

from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
minmax.fit(iris_df)
scale = minmax.transform(iris_df)

# transform으로 numpy ndarray로 변환된 데이터 
# dataFrame으로 변환하기

minmax_iris = pd.DataFrame(data=scale, columns=iris.feature_names)

print('feature의 최솟값 :',minmax_iris.min())
print('feature의 최댓값 :',minmax_iris.max())

feature의 최솟값 : sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature의 최댓값 : sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


학습 데이터와 테스트 데이터의 스케일링 변환 시 유의점
* 학습 데이터와 테스트 데이터의 스케일링 기준 정보 달라지지 않게 주의
* 머신러닝 모델은 학습 데이터를 기반으로 학습되기 때문에
* 반드시 테스트 데이터는 학습 데이터의 스케일러 기준에 따라야 함
* Scaler 객체를 이용해 학습 데이터 세트로 fit()과 transform()을 적용하면
* 테스트 데이터에 다시 fit()을 적용해서는 안 되며 
* 학습 데이터로 이미 fit()이 적용된 Scaler객체를 이용해 transform()으로 변환해야 함